# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitCode', models.CharField(max_length=60)),
                ('adminCode', models.CharField(max_length=60)),
            ],
        ),
    ]
